<a href="https://www.kaggle.com/code/rajeshkumarkarra/mathematics-for-machine-learning-and-data-science?scriptVersionId=239018165" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Introduction to Python Matrices and NumPy
# 1 - Basics of NumPy

## 1.1 Packages

In [1]:
import numpy as np

## 1.2 - NumPy arrays

In [2]:
# One dimensional array
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

# print("\n") # creating space between the output
print()
# Two dimensional array
two_dimensional_arr = np.array(
    [
        [10, 20],
        [30, 40]
    ]
)
print(two_dimensional_arr)

#print("\n")
print()

# Create an array with 3 integers, starting from the default integer 0
# np.arange()
arr_of_three = np.arange(3)
print(arr_of_three)

print()

# Create an arry that starts from the integer 1, and ends at 20, incremented by 3
# np.arange()
arr_inc_by_three = np.arange(1, 20, 3)
print(arr_inc_by_three)

print()

# An array with evenly spaced values
# np.linspace()
arr_with_evenSpace = np.linspace(0, 100, 5)
print(arr_with_evenSpace)

[10 12]

[[10 20]
 [30 40]]

[0 1 2]

[ 1  4  7 10 13 16 19]

[  0.  25.  50.  75. 100.]
