<a href="https://www.kaggle.com/code/rajeshkumarkarra/mlx-apple?scriptVersionId=248893358" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
!pip3 install mlx

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 57.8 MB/s eta 0:00:00


# Basics


In [2]:
import mlx.core as mx

a = mx.array([1,2,3,4])
a.shape
a.dtype

b = mx.array([1.0, 2.0, 3.0, 4.0])
b.dtype

print(a)
print(b)

array([1, 2, 3, 4], dtype=int32)
array([1, 2, 3, 4], dtype=float32)


$eval()$, $numpy.ndarry$

In [3]:
c = a + b # c not yet evaluted
print('before evaluted', c)
mx.eval(c) # evaluates c
c = a + b
print('after evaluted', c)  # Also evaluates c

c = a + b
print(c)
import numpy as np
import dask.array as da

np.array(c) # Also evaluates c
print(c)





before evaluted array([2, 4, 6, 8], dtype=float32)
after evaluted array([2, 4, 6, 8], dtype=float32)
array([2, 4, 6, 8], dtype=float32)
array([2, 4, 6, 8], dtype=float32)


In [4]:
# Lazy Evaluation
def fun1(x):
    return x + 1 # Dummy implementation
def expensive_fun(a):
    return a **2 

def fun(x):
    a = fun1(x)
    b = expensive_fun(a)
    return a, b
x = 5
y, _ = fun(x)
print("y = ", y)

y =  6


# Functions and Graph Transformations